noremap! \art 🎨
noremap! \zzap ⚡️
noremap! \fire 🔥
noremap! \bug 🐛
noremap! \ambulance 🚑️
noremap! \sparkles ✨
noremap! \memo 📝
noremap! \rocket 🚀
noremap! \lipstick 💄
noremap! \tada 🎉
noremap! \cmark ✅
noremap! \lock 🔒️
noremap! \lkey 🔐
noremap! \bookm 🔖
noremap! \rlight 🚨
noremap! \constr 🚧
noremap! \gheart 💚
noremap! \adown ⬇️
noremap! \aup ⬆️
noremap! \pushpin 📌
noremap! \cwork 👷
noremap! \upward 📈
noremap! \recycle ♻️
noremap! \hps ➕
noremap! \hms ➖
noremap! \wrench 🔧
noremap! \hammer 🔨
noremap! \globe 🌐
noremap! \pencil2 ✏️
noremap! \poop 💩
noremap! \rewind ⏪️
noremap! \twisted 🔀
noremap! \package 📦️
noremap! \alien 👽️
noremap! \truck 🚚
noremap! \pageup 📄
noremap! \boom 💥
noremap! \bento 🍱
noremap! \wheelc ♿️
noremap! \bulb 💡
noremap! \beers 🍻
noremap! \sballoon 💬
noremap! \cbox 🗃️
noremap! \loud_sound 🔊
noremap! \mute 🔇
noremap! \silh 👥
noremap! \ccrossing 🚸
noremap! \crane 🏗️
noremap! \iphone 📱
noremap! \clown 🤡
noremap! \egg 🥚
noremap! \noevil 🙈
noremap! \cflash 📸
noremap! \alembic ⚗️
noremap! \mag 🔍️
noremap! \label 🏷️
noremap! \seedling 🌱
noremap! \rflag 🚩
noremap! \goal 🥅
noremap! \dizzy 💫
noremap! \wbask 🗑️
noremap! \passp 🛂
noremap! \bandage 🩹
noremap! \monocle 🧐
noremap! \coffin ⚰️
noremap! \ttube 🧪
noremap! \necktie 👔
noremap! \stethoscope 🩺
noremap! \bricks 🧱
noremap! \techn 🧑‍💻
noremap! \moneyw 💸
noremap! \thread 🧵
noremap! \safety 🦺
